image:
  file: .gitpod.Dockerfile

tasks:
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    init: go get && go build ./... && go test ./...
    command: go run

vscode:
  extensions:
    - WakaTime.vscode-wakatime@4.0.0:rqaJxs4aJXm7PkF6R8Rw0Q==